services:
  # Serviço da Aplicação Spring Boot StreamFlow (Produção)
  prd-app-streamflow:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: streamflow_app_prd
    restart: unless-stopped
    networks:
      - prd-streamflow-network
    ports:
      - "${PORT:-8084}:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prd}
      - APP_ACCESS_PASSWORD=${APP_ACCESS_PASSWORD}
      - APP_ADMIN_KEY=${APP_ADMIN_KEY}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      - CLOUDFLARE_CALLS_APP_ID=${CLOUDFLARE_CALLS_APP_ID}
      - CLOUDFLARE_CALLS_APP_SECRET=${CLOUDFLARE_CALLS_APP_SECRET}
      - CLOUDFLARE_CALLS_ACCOUNT_ID=${CLOUDFLARE_CALLS_ACCOUNT_ID}
      - CLOUDFLARE_CALLS_ANALYTICS_TOKEN=${CLOUDFLARE_CALLS_ANALYTICS_TOKEN}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - JAVA_TOOL_OPTIONS=-Duser.timezone=America/Sao_Paulo
      - TZ=America/Sao_Paulo

networks:
  prd-streamflow-network:
    external: true
